# Generated by Django 3.2.13 on 2023-02-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graduation',
            field=models.IntegerField(blank=True),
        ),
    ]
